# Generated by Django 4.2.23 on 2025-08-03 14:36

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gig',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('attended', 'Attended')], default='attended', max_length=10),
        ),
        migrations.CreateModel(
            name='GigImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Gig Image')),
                ('is_cover', models.BooleanField(default=False, help_text='Set as cover image for the gig')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gigs.gig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_cover', 'id'],
            },
        ),
    ]
