# Generated by Django 4.2.23 on 2025-08-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_genre_alter_gig_options_gig_status_gigimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gigs.venue'),
        ),
    ]
