# Generated by Django 4.2.23 on 2025-08-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_alter_gig_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
