# Generated by Django 4.2.23 on 2025-08-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_venue_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='venue',
        ),
        migrations.AddField(
            model_name='gig',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
