# Generated by Django 4.2.23 on 2025-08-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_remove_gig_venue_gig_venue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='gig',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gigs.venue'),
        ),
        migrations.AddField(
            model_name='gig',
            name='venue_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gig',
            name='venue_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gig',
            name='venue_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='venue_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='venue',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
