# Generated by Django 4.2.23 on 2025-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_rename_location_venue_city_gig_venue_gig_venue_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='venue_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='venue_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
