# Generated by Django 4.2.23 on 2025-08-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_alter_gig_venue_lat_alter_gig_venue_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='longitude',
        ),
    ]
