# Generated by Django 4.2.23 on 2025-08-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_remove_venue_latitude_remove_venue_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='venue_city',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='venue_country',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='venue_lat',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='venue_lng',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='venue_name',
        ),
    ]
