# Generated by Django 4.2.23 on 2025-08-16 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0010_remove_gig_venue_city_remove_gig_venue_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Paste a YouTube link (watch, youtu.be, shorts ok)')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_time', models.PositiveIntegerField(blank=True, help_text='Optional start time in seconds (e.g. 95)', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gigs.gig')),
            ],
            options={
                'ordering': ['-is_featured', '-added_at'],
            },
        ),
    ]
