# Generated by Django 4.2.23 on 2025-08-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0011_gigvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigvideo',
            name='start_time',
        ),
    ]
